### ISSUE TITLE
Python 3.12 re-build failed to deploy

### ISSUE THREAD

**Issue by IAlibay** [conda-forge/biopython-feedstock#42]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi,

The build for the recently merged #41 failed to deploy due to timeout issues, could one of the feedstock maintainers make a new build?

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by peterjc** [comment]
How? Just a PR which bumps the build number, or something else like reruning the failed CI task?

**Comment by IAlibay** [comment]
I believe you can just go ahead and create a new PR without updating the build number - just checking this with #43 and #44

**Comment by peterjc** [comment]
Closed via #44, see https://anaconda.org/conda-forge/biopython/files
